### ISSUE TITLE
3dm-gx5-10

### ISSUE THREAD

**Issue by Sanderi44** [LORD-MicroStrain/ROS-MSCL#1]
Hello,
Thank you for providing this driver. I am currently bringing up a 3dm-gx5-10 IMU and have found that the ros_mscl driver throws a ton of ROS_ERROR's and is very slow. I was able to get the driver up and running at a faster pace, but wanted to report how I did it. I will also make a PR to update the driver. 

The ROS_ERROR's that I received included a few variations of:
`Error: The systemState option has not been set`
Where other properties besides systemState were also not set. 

The reason for this bug was that the MSCL driver does not set those properties, like it does for the rest of the 3dm-gx5-15 to 45 IMU's. To fix the bug, I check that the version of the IMU is not 3dm-gx5-10, and if it is, just don't look for the offending values in the loop. 

The slowness of the driver was due to the `print_packet_stats()` function. There are 4 try-catch's in there that are slowing things down drastically. Removing or making that function optional is the best way to fix this issue.

**Comment by rdslord** [comment]
Thanks for reaching out! 

We updated MSCL and ROS-MSCL to solve the problem of unset properties in the status messages. This also eliminated the need for those try-catch blocks in print_packet_stats. If you get the latest versions of each, you should find that the driver runs significantly faster.
