### ISSUE TITLE
does the driver work Microstrain 3DM-GX5-25 on ros foxy?

### ISSUE THREAD

**Issue by Sollimann** [LORD-MicroStrain/ROS-MSCL#125]
I see there is a ros2 branch of this repo that seems to be actively maintained. Has it been tested with the Microstrain 3DM-GX5-25 on ros2 foxy? 

Keep up the good work!

**Comment by robbiefish** [comment]
Hi @Sollimann, yes the `ros2` branch does work with the 3DM-GX5-25 on ROS2 foxy. The driver can be installed for foxy [from source](https://github.com/LORD-MicroStrain/microstrain_inertial#source), by using one of the `-foxy` tags from [dockerhub](https://hub.docker.com/r/microstrain/ros-microstrain_inertial_driver), or from the [ROS package index](https://index.ros.org/p/microstrain_inertial_driver/github-LORD-MicroStrain-microstrain_inertial/#foxy) with `sudo apt-get install ros-foxy-microstrain-inertial-driver`.

Please let us know if you run into any problems using the 3DM-GX5-25 with the driver.
