### ISSUE TITLE
IMU filter does not remove gravity

### ISSUE THREAD

**Issue by ghost** [LORD-MicroStrain/ROS-MSCL#127]
The IMU filtered output does not remove the gravity according to the pitch and roll.
We have been using the package version of 08/2020 and it does work well. Updating to 2.4.1 introduced the issue.
Sensor - 3DM-GX5-25

**Comment by robbiefish** [comment]
Hi @AARobotics, thanks for bringing this to our attention. Many users want to have gravity in the acceleration measurements, so this has been added as a parameter to the launch file in #128 for ROS and #129 for ROS2.

If you have a setup where you can test this, could you please try to checkout either the [featue/ros_filter_imu_linear_accel](https://github.com/robbiefish/microstrain_inertial/tree/feature/ros_filter_imu_linear_accel) for ROS, or [featue/ros_filter_imu_linear_accel](https://github.com/robbiefish/microstrain_inertial/tree/feature/ros2_filter_imu_linear_accel) for ROS2, change the `filter_use_compensated_accel` to False, and let us know if it did or did not work for you? If you do not have somewhere to test, please let me know.
