### ISSUE TITLE
 IMU's yaw angle drift

### ISSUE THREAD

**Issue by yaodongC** [LORD-MicroStrain/ROS-MSCL#142]
**Describe the bug**
GX5-25 IMU's yaw angle is malfunction (yaw drift).
Description of yaw drift:
When we turn the yaw angle of IMU 90 degrees and stoped turning. The yaw angle output will first reach 90 degrees, but will very soon start to decrease to around 40-50 degrees.
Note:
1. **Pitch and roll angle output is normal and no drift is observed**.
2. Yaw drifting is observed when using the official LORD repo and the ROS microstrain repo in Ubuntu env
3. We notice the **yaw angle is normal when tested in Windows 10 using the official desktop software SensorConnect from LORD**.
4. GX5-25 is on the latest firmware (v.1.1.76 and v1.1.05 for NAV and IMU)
Thanks

**To Reproduce**
Rosbag of yaw drift:
https://drive.google.com/file/d/1WH2O9vZIyskxiN7unuE6WtaA5M-1Tg01/view?usp=sharing

**Comment by robbiefish** [comment]
Hi @yaodongC, Thanks for this information. Could you please provide the launch file, or parameter file you are using to configure the device?

Have you been testing the device while it is mounted on a robot? If so, when you tested the device with SensorConnect, did you remove the device from your robot to test it, or did you test the device while it was still mounted on the robot?
