### ISSUE TITLE
About 3DMGX5-AHRS Euler angle 

### ISSUE THREAD

**Issue by FrozenCo** [LORD-MicroStrain/ROS-MSCL#147]
I want to know whether the Euler angle of this IMU corresponds to the figure below, that is the X axis corresponds to pitch, the Y axis corresponds to roll, and the Z axis corresponds to yaw. As shown below.
![image](https://user-images.githubusercontent.com/103629575/164597770-a07d8f30-b452-4aa1-904e-1fbad89ee8f8.png)
And I want to know if I can modify the drive so that the axis of IMU can correspond to the axis of lidar.
Thanks!!!!!

**Comment by nathanmillermicrostrain** [comment]
Hi zyx,

The rotations about the IMU axis are not as described in the image above.  A roll would be around the x axis, a pitch about the y, and a positive rotation on the z axis is in the opposite direction shown in the image.

To answer your question, we provide a sensor2vehicle transformation in the driver that will allow for the axis to change, but not the + rotation direction. For your purposes, it would be a yaw of 180, a roll of 180, and a pitch of 0.   So you could use the Euler angle definition and put in [0, 3.14, 3.14]  (these are in roll, pitch, yaw order.)

filter_sensor2vehicle_frame_selector : 1
filter_sensor2vehicle_frame_transformation_euler : [0.0, 3.14, 3.14]

Hope that helps!

Nathan

**Comment by zyx-99** [comment]
> 

thanks for your reply! but the parameter setting still confusing me.
as you say.it would be a yaw of 180, a roll of 180, and a pitch of 0. 
if the parameter should be set as [3.14,0.0,3.14](these are in roll, pitch, yaw order.) 
rather than
[0, 3.14, 3.14] (these are in roll, pitch, yaw order.)

**Comment by FrozenCo** [comment]
> Hi zyx,
> 
> The rotations about the IMU axis are not as described in the image above. A roll would be around the x axis, a pitch about the y, and a positive rotation on the z axis is in the opposite direction shown in the image.
> 
> To answer your question, we provide a sensor2vehicle transformation in the driver that will allow for the axis to change, but not the + rotation direction. For your purposes, it would be a yaw of 180, a roll of 180, and a pitch of 0. So you could use the Euler angle definition and put in [0, 3.14, 3.14] (these are in roll, pitch, yaw order.)
> 
> filter_sensor2vehicle_frame_selector : 1 filter_sensor2vehicle_frame_transformation_euler : [0.0, 3.14, 3.14]
> 
> Hope that helps!
> 
> Nathan

thanks for your reply! but the parameter setting still confusing me.
as you say.it would be a yaw of 180, a roll of 180, and a pitch of 0.
if the parameter should be set as [3.14,0.0,3.14](these are in roll, pitch, yaw order.)
rather than
[0, 3.14, 3.14] (these are in roll, pitch, yaw order.)

**Comment by nathanmillermicrostrain** [comment]
Yep, you're right. [3.14, 0, 3.14]

**Comment by FrozenCo** [comment]
> Yep, you're right. [3.14, 0, 3.14]
Thanks a lot.

**Comment by FrozenCo** [comment]
> Hi zyx,
> 
> The rotations about the IMU axis are not as described in the image above. A roll would be around the x axis, a pitch about the y, and a positive rotation on the z axis is in the opposite direction shown in the image.
> 
> To answer your question, we provide a sensor2vehicle transformation in the driver that will allow for the axis to change, but not the + rotation direction. For your purposes, it would be a yaw of 180, a roll of 180, and a pitch of 0. So you could use the Euler angle definition and put in [0, 3.14, 3.14] (these are in roll, pitch, yaw order.)
> 
> filter_sensor2vehicle_frame_selector : 1 filter_sensor2vehicle_frame_transformation_euler : [0.0, 3.14, 3.14]
> 
> Hope that helps!
> 
> Nathan

so sorry to bother you again. but could you tell me if I set "use_enu_frame" to TRUE in ROS driver. what should the coordinate looks like.
![cos solepic_edit_84011983792907](https://user-images.githubusercontent.com/103629575/165542334-54f414da-079b-4dd5-af30-03e021a6f307.jpg)
as shown in the image above. the device only describes the NED coordinate system.

**Comment by nathanmillermicrostrain** [comment]
Hi zyx,

All of our devices are NED natively... the ENU coordinate system is provided in the ROS driver as a convenience to customers.  If you select ENU, the coordinates on the unit will be as follows:

![image](https://user-images.githubusercontent.com/69481927/165556348-3b60927b-0f51-4290-934a-f89607815bb7.png)
