### ISSUE TITLE
Need raw output of gnss1 and gnss2 antenna heading in gnss topics

### ISSUE THREAD

**Issue by ozangerger** [LORD-MicroStrain/ROS-MSCL#153]
**Is your feature request related to a problem? Please describe.**
I need a raw heading value read from gnss1 and gnss2, which I can clearly see from sensorcloud data interface.

**Describe the solution you'd like**
in /gnss1/fix or /odom topic, I would like to see the raw heading angle for each gnss antenna.

**Describe alternatives you've considered**
Calibration of IMU sensor is complicated at this level and /nav/filtered_imu/data.orientation reading is not stable in our application. I just need a simple heading reading from gnss1 and gnss2. 

**Additional context**

**Comment by robbiefish** [comment]
This is now availble in 4.0.0 in the GNSS odometry messages
