### ISSUE TITLE
Are there IDL files for ROS2/DDS usage of the ROS MSG files?

### ISSUE THREAD

**Issue by stewy-lewy-TR** [LORD-MicroStrain/ROS-MSCL#155]
I am trying to use DDS for my application, and need access to the IDL files to use the messages to create specific topics. I was looking through the current repository and didn't find any IDL files. I specifically am trying to use the ros2_mscl_interfaces/msg/MSCLFilterStatus message type.

**Comment by robbiefish** [comment]
Hi @stewy-lewy-TR,

Yes, we have IDL files located in the `microstrain_inertial_mgs/microstrain_inertial_msgs_common` directory of this repo. This directory is a submodule, and can be found [here](https://github.com/LORD-MicroStrain/microstrain_inertial_msgs_common).

I am unfamiliar with `ros2_mscl_interfaces/msg/MSCLFilterStatus`, but it sounds like you are looking for our [`FilterStatus.msg`](https://github.com/LORD-MicroStrain/microstrain_inertial_msgs_common/blob/main/msg/FilterStatus.msg)

**Comment by stewy-lewy-TR** [comment]
@robbiefish yes I'm looking for the IDL file for the FilterStatus.msg. I clicked on that location and only see the msg folder.

**Comment by robbiefish** [comment]
FilterStatus.msg is located in that folder. Here is a link directly to the FilterStatus.msg file:

[https://github.com/LORD-MicroStrain/microstrain_inertial_msgs_common/blob/main/msg/FilterStatus.msg](https://github.com/LORD-MicroStrain/microstrain_inertial_msgs_common/blob/main/msg/FilterStatus.msg)
