### ISSUE TITLE
Publish filtered LLH position as a NavSatFix message. 

### ISSUE THREAD

**Issue by ghost** [LORD-MicroStrain/ROS-MSCL#163]
The current method of publishing the filtered LLH into a nav_msgs/Odometry message is confusing and not easily used by many common ROS packages, such as Robot Localization,  that are expecting this sort of information as a sensor_msgs/NavSatFix message, or, an Odometry message with pose with X,Y,Z measured in meters from an initial frame.

Issue 133 references this same problem. And mentions "We realize that this is a little confusing to populate an Odometry message with LLH position, and are looking at possible alternatives." For our use case, having this information published in a sensor_msgs/NavSatFix message would be a much better fit for this information and is set up to handle Latitude, Longitude, and altitude.

**Comment by robbiefish** [comment]
This functionality is available in `4.0.0` and above
