### ISSUE TITLE
Running the GQ7 the second time creates an "Error: Failed to communicate with device"

### ISSUE THREAD

**Issue by echoGee** [LORD-MicroStrain/ROS-MSCL#172]
**Describe the bug** **To Reproduce**
-Run the roslaunch command to start streaming the gq7. 
-Kill the ros node
-Rerun the ros node with the exact same command. This results in "Error: Failed to communicate with device"
- The solution to this is unplugging and replugging the main and aux ports
**Expected behavior**
Should work everytime without replugging 

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Architecture: arm64
 - ROS Version: noetic
 - Version: [e.g. 2.0.0]
 - Sensor(s): 3DM-GQ7

**Additional context**
![image (1)](https://user-images.githubusercontent.com/518314/183130688-dafca7da-93ba-415b-a580-5e2158ebbe53.png)

**Comment by robbiefish** [comment]
Hi @echoGee,

I have installed the udev rules and the driver on a Jetson Xavier and was unable to reproduce this behavior. I have a couple questions to help me debug:

1. What version of the driver are you using? Can be found with `rosversion microstrain_inertial_driver`
2. Assuming you are using a Jetson as well, you are likely using some sort of USB to USB-C adapter (if not please ignore these sub questions)
    * Are both the main and aux port plugged into the same adapter and have you tried testing with only the main port connected?
    * Have you tried using a different adapter?
3. Could you please provide me with the output from the following commands?
    a. `udevadm info -a -n "$(readlink -f /dev/microstrain_main)" | grep serial`
    b. `udevadm info -a -n "$(readlink -f /dev/microstrain_aux)" | grep serial`
    c. `ll /dev/microstrain_*`
