### ISSUE TITLE
catkin make    microstrain_3dm.cpp failed

### ISSUE THREAD

**Issue by xhzhu-robotic** [LORD-MicroStrain/ROS-MSCL#18]
![Screenshot from 2020-09-02 10-10-54](https://user-images.githubusercontent.com/46907469/91994397-154b0680-ed26-11ea-8356-c9bb4e0ddac4.png)

**Comment by rdslord** [comment]
What version of MSCL do you have installed?

**Comment by xhzhu-robotic** [comment]
The latest version. I just use git clone command to download the file.

**Comment by xhzhu-robotic** [comment]
I just misunderstand it. My MSCL is not the latest version. I will upgrade it and see whether it works.

**Comment by xhzhu-robotic** [comment]
It works when I upgrade MSCL to latest version. Thanks!
