### ISSUE TITLE
How do i fix yaw drift?

### ISSUE THREAD

**Issue by Byeongcheol-Jeon** [LORD-MicroStrain/ROS-MSCL#217]
I am using 3dm-cv7-ahrs.

The thing is yaw data automatically moves. And I understand that it is because there is drift by Earth's rotation.

I've heard that complementary filter or AHRS algorithm can correct this issue.

But I dont know how to use or apply these methods.

Could you please tell me how to?

Thanks

**Comment by nathanmillermicrostrain** [comment]
Hello,

The yaw reported from the device will be from the AHRS algorithm.  Please make sure the magnetometer heading is enabled in the driver with the following setting:

filter_enable_magnetometer_aiding : True
