### ISSUE TITLE
how to know the euler angle through imu/data

### ISSUE THREAD

**Issue by himhan34** [LORD-MicroStrain/ROS-MSCL#219]
is there any ways to know the orientation through pure imu/data?
as i seen in the imu/data converted from the bag file that i recorded, 
i can see the quaternion x,y,z,w in the imu/data is there any method to do exact roll pitch yaw through the imu/data?

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: x86_64,
 - ROS Version: melodic,
 - Version: [e.g. 2.0.0]
 - Sensor(s):  3DM-GQ7

now i am using the 3DM-GQ7 to use slam with LIOSAM, but to do the right mapping in the slam 
i have to know the exact euler axis for the imu, is there any ways to do that?

**Comment by nathanmillermicrostrain** [comment]
Hello,

It is a bit unclear to me what you are asking for... are you asking how to convert the quaternion to Euler roll, pitch. yaw angles?  If this is the case, there are transformation routines in ROS to do this (http://wiki.ros.org/tf2)  If you are asking for something different, could you explain a bit more so I can provide you the correct answer?

Thank you,

Nathan
