### ISSUE TITLE
enableDataStream

### ISSUE THREAD

**Issue by Boss-Zheng** [LORD-MicroStrain/ROS-MSCL#220]
**Describe the bug**
I keep getting errors(mscl.Error_MipCmdFailed:"The ContinuousDataStream command has failed) when calling commands(nodeIMU.enableDataStream(mscl.MipTypes.DataClass.CLASS_AHRS_IMU, true)) using C# code. Calls to other relevant data stream code will also report errors, for example, nodeIMU.isDataStreamEnabled(mscl.MipTypes.DataClass.CLASS_AHRS_IMU);

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Architecture: [e.g. x64]
 - Compiler: [e.g. Visual Studio2017]
 - Sensor(s): [e.g.3DM-GX5-AR]

**Comment by robbiefish** [comment]
This appears to be a problem with MSCL and not the ROS driver. Please open an issue on the [MSCL issues](https://github.com/LORD-MicroStrain/MSCL/issues) page
