### ISSUE TITLE
Vehicle Reference Point

### ISSUE THREAD

**Issue by Jad-Tawil** [LORD-MicroStrain/ROS-MSCL#221]
Has the driver been updated to support the Vehicle Reference Point command?

**Comment by robbiefish** [comment]
Hi @Jad-Tawil,

Yes, it can be configured in the params.yml [here](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/main/config/params.yml#L276-L279).

Please note that this change is only in the [`ros`](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros) and [`ros2`](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros2) branches and has not been released to the ROS package index yet, so you will need to build from source to get this feature
