### ISSUE TITLE
About topic '/gx5/nav/filtered_imu/data'

### ISSUE THREAD

**Issue by isValid** [LORD-MicroStrain/ROS-MSCL#23]
I updated the dependent libraries(v58.0.7) and packages. 
Then I modified some parameters in the launch file:
filter_sensor2vehicle_frame_selector: 0->3
filter_heading_source: 1->0
After I started GX5-25.
The topic '/gx5/nav/filtered_imu/data' show:
orientation: x:0 y:0 z:0 w:1
linear_acceleration: x:0 y:0 z:0
I think there is a problem, can you please check.

**Comment by nathanmillerparker** [comment]
If your filter heading source is "0", the kalman filter will not initialize without an initial heading.  You will need to use the InitFilterHeading service or the InitFilterEuler to initialize the filter.

**Comment by isValid** [comment]
OK,thank you, I change the heading source is "1", I can get the orientation and linear_acceleration data, but the z value of linear_acceleration is close to 0, it seems it should be -9.8, like the data before filtering?

**Comment by isValid** [comment]
[](url)

**Comment by nathanmillerparker** [comment]
The linear acceleration excludes gravity

**Comment by isValid** [comment]
There is gravitational acceleration before filtering but not after filtering?

**Comment by nathanmillerparker** [comment]
For that data quantity, yes.  If we didn't remove gravity, it would have just been a copy of what comes from IMU.. this is a convenience quantity that some of our customers have asked for.

**Comment by isValid** [comment]
Okay, I understand, so if I need, I can use the linear acceleration of IMU

**Comment by nathanmillerparker** [comment]
Yep

**Comment by isValid** [comment]
ok,thank you~
