### ISSUE TITLE
COMMUNICATION ERROR when using the WSDA-200_USB

### ISSUE THREAD

**Issue by JosuavanTonder** [LORD-MicroStrain/ROS-MSCL#232]
Hi all , trust everyone is doing well 

I am attempting to set up a multisensor network, I plan to use the WSDA-200_USB and a gateway for an SG-LINK-200, V-LINK-200 and a G-LINK. However, when using the SensorConnect software the Base Station connect initially and seems to work, but when attempting to connect nodes or set the Beacon to ON the communication error is given. 

I have installed the drivers and checked for updates, reinstalled the software and some other steps. 

has anyone else encountered a similar problem or at least point me in the right direction? 

I would like to add that I am new to the LORD wireless connection ecosystems, so I might have made some obvious errors. 

Any help would be much appreciated.

**Comment by robbiefish** [comment]
Hi @JosuavanTonder,

This question seems to be more related to SensorConnect, which is not relevant to the ROS driver. Please reach out to support at: microstrainsupport@parker.com and we will be happy to help
