### ISSUE TITLE
Additional Doccumentation on coridinate reference for GNSS, ODOM, and TF topics

### ISSUE THREAD

**Issue by CaptKrasno** [LORD-MicroStrain/ROS-MSCL#242]
**Is your feature request related to a problem? Please describe.**
I am in the process of setting up our new 3DMGQ7-GNSS/INS.    I was able to get it powered up and working with the ROS2 node.   However, I find the geographic frame setup quite unclear.   For example, with the default configuration.    

- The published TF (in the tf tree) broadcasts at transform form `sensor_wgs84` to `sensor`.    This seems to correspond to the data present in nav/relative_pos/odom. This leads me to believe that this should be relative to an RTK base station which is not currently implemented.     
- in `nav/relative_pos/odom` and `tf` I am getting a potion of ~(-17,611, 0.0, -6,373,488) which doesn't seem to correspond to anything physical in ECEF or LLA.   The LLA position in `gnss1/fix` is correct. 
- **Question: where is `sensor_wgs84' relative to Earth?** 
-  the `/gnss*/odom/` odom topics apparently pack the pose position with x=lat, y=lon, z=height above ellipsoid.   as a non-standard implementation of `nav_msgs/Odomentry` this should be clearly documented.  

**Describe the solution you'd like**

- Clear, detailed documentation how coordinate frames are defined, especially with regard to geodetic coordinates.  
- A clear description of what each topic means for example:
  - `nav/odom` vs `nav/relative_pos/odom`
  - `imu/data` vs `imu/filtered_imu/data`
  - the above example are somewhat clear from the naming but clear documentation would be useful to avoid misunderstandings or bad assumptions.   A few words describing each topic would go a long way.  
- 

**Describe alternatives you've considered**
I have found an early version of the documentation describing the topics [on the ros wiki](http://wiki.ros.org/microstrain_inertial_driver/devices/archive) I have not been able to find anything for the latest versions or ros2

**Comment by robbiefish** [comment]
Messages should be more standard now, and the [wiki page](https://wiki.ros.org/microstrain_inertial_driver) has been updated to document these changes and any remaining oddities
