### ISSUE TITLE
3DM-GQ7always produces zero Y values

### ISSUE THREAD

**Issue by CaptKrasno** [LORD-MicroStrain/ROS-MSCL#244]
**Describe the bug**

Upon running the internal driver for the GQ7 with the default parameters (other than changing the serial port) I only ever receive  Y values of zero (or very near zero +/- ~1e-10) on `/nav/relative_pos/podom` and on `tf`.  The image below shows a plot of this behavior and a rostopic echo of a message for reference.

![Screencast from 03-27-2023 11:48:22 AM](https://user-images.githubusercontent.com/23006525/227995954-bf4889d0-e46e-42c5-aad7-aa783e7a5585.gif)

```
$ ros2 topic echo /nav/relative_pos/odom
header:
  stamp:
    sec: 1679932693
    nanosec: 134000000
  frame_id: sensor_wgs84
child_frame_id: sensor
pose:
  pose:
    position:
      x: -17611.411584795453
      y: -5.820766091346741e-10
      z: -6373479.216126954
    orientation:
      x: 0.0023351265117526054
      y: -0.002072608796879649
      z: 0.4364275336265564
      w: 0.8997340202331543

...

```

These position values don't seem to make any physical sense in either LLA , ECEF, ENU, or NED.   

**To Reproduce**
1. `ros2 launch microstrain_inertial_driver microstrain_launch.py configure:=true activate:=true debug:=true params_file:=sensor_a_params.yml `

**Expected behavior**
I would expect both `/nav/relative_pos/podom`  on `tf` to publish positions in ECF, ENU, or NED depending on configuration.   In any case the y component should not be fixed at zero.     

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture:  x86_64
 - ROS Version: Humble
 - Version: from source 63c02dd454daa1a9d77fd90856d903438831e7c1
 - Sensor(s):  3DM-GQ7

**Modifications**
None

**Launch Parameters**
sensor_a_params.yml:
```
microstrain_inertial_driver:
  ros__parameters:
    port: /dev/ttyUSB0
```

**Comment by robbiefish** [comment]
Hi @CaptKrasno,

Apologies for the delay in my response. I am able to see the same behavior. This appears to happen when the `Reference Coordinates` of the [`Relative Position Configuration`](https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Commands/filter_command/data/mip_filter_rel_pos_configuration.htm?Highlight=relative) setting on the device have at least the x and y component set to 0.

I am working with our navigation engineers to determine why this is happening.

In the meantime, you should be able to fix this issue by configuring your relative position configuration [here](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/main/config/params.yml#L383) in the `params.yml`.

**Comment by CaptKrasno** [comment]
Thanks Rob,  (@robbiefish ) 

I set the relative position close to the operating location and got reasonable results.   Setting `filter_relative_position_ref` to very small values still gave strange behavior.   

**Although not optimal, this is good enough to get us testing this week.   Thanks for the quick fix.**   

Maybe this is a good time to back up:   Ultimately, I am looking to get an ECEF odometry message  from the device.  What is the intend way to do this in the ROS driver?  

I assumed the best way was to set the relative `filter_relative_position_ref:  [0,0,0]` with `filter_relative_position_frame: 1`.   After looking at the underlying MIP message though (relpos_ned), I can see how there is strange behavior  with `filter_relative_position_ref: [0,0,0]` since the rotation from ECEF to NED is ill defined with no translation between the two frames.   

I was able to get valid ECEF positions through  the "estimation filter Position(ECEF) MIP message" using sensor cloud connect.  However, it appears the driver doesn't subscribe to that message, at least in my configuration.   Is that supported in the ROS driver?

-Kris

**Comment by robbiefish** [comment]
At the moment, the ECEF position is not supported in the driver. There is no particular reason it cannot be supported, just a lack of time to implement the feature.

This is somewhat related to #214, but for an odometry message instead of a TF. If you could please open a new issue with a feature request for ECEF position in an odom message, we will get to it as soon as we can.

We are also always happy to review PRs if you were interested in implementing it yourself
