### ISSUE TITLE
Driver Should Attempt to Reconnect

### ISSUE THREAD

**Issue by vinnnyr** [LORD-MicroStrain/ROS-MSCL#246]
**Is your feature request related to a problem? Please describe.**
On our product, we are chasing some electrical / connection faults on the machine. 
When we use the driver, and the device connection is interrupted, we have to restart the process (docker container) to get access to the device again.

**Describe the solution you'd like**
I would like it so that the driver, upon sensing the device is no longer connected, at least logs / uses lifecycle to signify that the device is not connected. Better yet, we would like the device to attempt reconnecting.

**Describe alternatives you've considered**

**Additional context**
I guess this problem is resolved in our set up when we set
```
    # Controls if the driver-defined settings are saved
    #      false - Do not save the settings
    #      true  - Save the settings in the device's non-volatile memory
    save_settings: False 
```
parameter to `true` , but I still think that the driver should handle this case when `save_settings` is set to False.

**Comment by robbiefish** [comment]
This functionality is available in `4.0.0` of the driver, see [this section](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/3c7cc7ebf5fdd3db411a439de9c569cae15f214e/config/params.yml#L37) of the params.yml
