### ISSUE TITLE
Can we get GNSS raw measurements of 3DM gq7 like Ublox?

### ISSUE THREAD

**Issue by JokerJohn** [LORD-MicroStrain/ROS-MSCL#247]
**Is your feature request related to a problem? Please describe.**
I want to get the real-time GNSS raw measurements published by ros. like the UBX-RXM-RAWX(Multi-GNSS-Raw-Measurement Data), UBX-RXM-SFRBX and UBX-NAV-PVT  in Ublox F9p.  since we want to do a tightly-coupled methods with other sensors,such as camera and lidar.

**Describe the solution you'd like**
Multi-GNSS-Raw-Measurement, GNSS velocity(**not the 2 dimension speed from NMEA GPRMC**), and so on.

**Additional context**

![image](https://user-images.githubusercontent.com/25702851/232351217-18bcd2e6-7870-4aa8-aefa-f8d66d3c0d9c.png)

**Comment by nathanmillermicrostrain** [comment]
Hello,

The device outputs this information in our MIP format, please see these links for reference: https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/gnss_recv_1_links.htm
https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_2/gnss_recv_2_links.htm
https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_corrections/gnss_corrections_links.htm

We have not made this information available in our ROS driver yet as an overwhelming majority of our ROS customers use our computed solution.  There are provisions for accessing this information in the MIP SDK, which the driver is built on.  You could modify the driver code to collect and publish this data for your purposes.  If you choose to, please consider creating a pull request so others may benefit from it as well.  I will add a task to our backlog, but I cannot provide an estimate of when this may be complete.

Thank you,

Nathan

**Comment by JokerJohn** [comment]
> Hello,
> 
> The device outputs this information in our MIP format, please see these links for reference: https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_1/gnss_recv_1_links.htm https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_recv_2/gnss_recv_2_links.htm https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/gnss_corrections/gnss_corrections_links.htm
> 
> We have not made this information available in our ROS driver yet as an overwhelming majority of our ROS customers use our computed solution. There are provisions for accessing this information in the MIP SDK, which the driver is built on. You could modify the driver code to collect and publish this data for your purposes. If you choose to, please consider creating a pull request so others may benefit from it as well. I will add a task to our backlog, but I cannot provide an estimate of when this may be complete.
> 
> Thank you,
> 
> Nathan

Thank you for your patient response. I will try to complete this task and, if successful, I will contribute it.
