### ISSUE TITLE
Position covariance for topic /gx5/gnss1/fix

### ISSUE THREAD

**Issue by xhzhu-robotic** [LORD-MicroStrain/ROS-MSCL#26]
![Screenshot from 2020-10-29 10-16-28](https://user-images.githubusercontent.com/46907469/97615260-7a06a280-19f1-11eb-90ee-df6b7a9092b8.png)

Hi, 
I want to transfer gps data to global position at NED frame. So I need to get **current position covariance**. 

Based on the information in **/gps/gnss1/fix** , I founded that there are 'position covariance' and 'position covariance type' here. 

 I'm not sure what **'position covariance'** and **'position covariance type'** stand for in **/gx5/gnss1/fix** ? Is that for **latitude, longitude  and height**  not for global position at NED frame? In addition, could you tell me **how to change** position covariance type please?

I would appreciate it if you can help me.

**Comment by nathanmillerparker** [comment]
I believe the answers to your questions can be found here: http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/NavSatFix.html
