### ISSUE TITLE
Requesting help and advise (CV7-AHRS on Ubuntu 20)

### ISSUE THREAD

**Issue by roboomega** [LORD-MicroStrain/ROS-MSCL#265]
**Describe the bug**

My PC : Intel NUC 13 Pro Kit
OS : Ubuntu 20
Product : 3DM-CV7-AHRS (OEM)
Connection Type : oem micro 5 pin style adapter to USB

I connect to CV7-AHRS via micro 5 pin adapter connector
and connect to my PC via USB 2.x connector

I installed ROS1 (noetic) and executed

sudo apt-get update && sudo apt-get install ros-noetic-microstrain-inertial-driver

also, I did below

git clone --recursive --branch ros https://github.com/LORD-MicroStrain/microstrain_inertial.git ~/mstrain/src/microstrain_inertial

I also modified some paramters in params.yml

rosdep install --from-paths ~/mstrain/src -i -r -y
catkin_make
source ~/mstrain/devel/setup.bash
roslaunch microstrain_inertial_driver microstrain.launch

also in another terminal,
roslaunch microstrain_inertial_examples listener_cpp.launch

My questions are

1. There does nothing appear in the terminal where I did "roslaunch microstrain_inertial_examples listener_cpp.launch"
How can I make those sensor data appear on the screen terminal ?

2. I modified  params.yml file again
to make it create a bin file in the folder I designated
So, "roslaunch microstrain_inertial_driver microstrain.launch" commands created a bin file
Then what is the format of that bin file?
I attached the sample bin file below

[3DMCV7-AHRS_6286.167145_23_07_26_16_10_05.bin.txt](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12169920/3DMCV7-AHRS_6286.167145_23_07_26_16_10_05.bin.txt)

Below is the log of the command "roslaunch microstrain_inertial_driver microstrain.launch"

[mstrain_server_launch.log.txt](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12170106/mstrain_server_launch.log.txt)

Below is the log of the command "roslaunch microstrain_inertial_examples listener_cpp.launch"

[mstrain_example_launch.log.txt](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12170107/mstrain_example_launch.log.txt)

3. My final question is
I want to receive the sensor data on real time via ROS 1 noetic
How can I receive real time sensor data from it and how can select which data among all data I receive?

Also, I want to save the sensor data into a file via ROS 1 noetic too

I will appreciate if you can help me with this issues

Thank you

An Engineer
Nexreal Inc.
Seoul

**To Reproduce**

1.
In one terminal, execute
roslaunch microstrain_inertial_driver microstrain.launch

In other terminal, execute
roslaunch microstrain_inertial_examples listener_cpp.launch

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Architecture: x64 Intel
 - ROS Version: Noetic
 - Version: rosversion 1.16.0
 - Sensor(s): 3DM-CV7-AHRS (OEM)

**Modifications**
Did you modify the source code in any way while testing? If so, please note those modifications here.

I modified the params.yml

**Launch Parameters**
If you have an updated `params.yml` file, please attach it to this issue.
[params.yml.txt](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12169864/params.yml.txt)

**Additional context**

Below is the bin file generated from SensorConnect Program on Windows 10

[3DM-CV7-AHRS_6286.167145_20230726T080120Z.bin.txt](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12170139/3DM-CV7-AHRS_6286.167145_20230726T080120Z.bin.txt)

**Comment by robbiefish** [comment]
Hi @roboomega,

If you update to version `4.0.0` or later of the ROS driver, you can use the [CV7 Example](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros/microstrain_inertial_examples#cv7--gv7) that we have posted to get started with your CV7.

Receiving realtime sensor data can be done by subscribing to the topics you are interested in. You can check out [our wiki](https://wiki.ros.org/microstrain_inertial_driver) for more information on what those topics are. Please see the ROS documentation for how to do this in [Python](https://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29) and [C++](https://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29)
