### ISSUE TITLE
segfault on deactivate when aux_device_ not nullptr

### ISSUE THREAD

**Issue by YairBarzilayBWR** [LORD-MicroStrain/ROS-MSCL#270]
in microstrain_inertial_drvier.cpp inside run(), when the config sets aux_device to a shared ptr, meaning it is not a nullptr, then a timer for the aux parser is not created.

![image](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/101091115/382edf73-fc61-49d1-98e7-86f6d4000998)

then when shutting down and deactivating, inside NodeCommon::deactivate() we call stopTimer(aux_parsing_timer_); and a segfault occurs because the timer aux_parsing_timer_ was never created.

**Comment by robbiefish** [comment]
This was fixed in version `4.0.1` of the driver
