### ISSUE TITLE
INS level arm related to ground car rear axle

### ISSUE THREAD

**Issue by ayoubasritii** [LORD-MicroStrain/ROS-MSCL#274]
**Describe the bug**
I'm currently using your GQ7 (INS) on a buggy project and have encountered some issues that I'm hoping you could help me resolve.

Vehicle Reference Point Offset: Our INS is installed on a buggy. The system is shifted 8cm from the X axis and positioned 1 meter in front of the rear axle, where the lateral velocity is zero. I have activated the automotive model and Wheeled Vehicle Constraint in the system. However, I am unsure how to configure the INS to account for the 1-meter distance from the rear axle (very important for the ackerman model). I suspect that this involves setting the Vehicle Reference Point Offset, but I am not certain. Could you confirm if this is the case, and if so, provide the syntax for the relevant command to be added to the microstrain.yaml file?

Issue with INS Solution: I have attempted some tests without setting the Vehicle Reference Point Offset. While the antenna positions are accurate, I noticed some discrepancies in the INS solution, especially during turns. I've attached a bag file, the microstrain.yaml file, and the configuration exported using SensorConnect for your reference.
[Inquiry on INS GQ7 Configuration.zip](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12482841/Inquiry.on.INS.GQ7.Configuration.zip)

EDIT: After Barry's response, I updated the firmware to the latest version, set the reference lever arm to the rear axle (the param wasn't available before in SensorConnect), and tested it again. Unfortunately, I got the same results. You will find attached the new recording.
[new_firmware.zip](https://github.com/LORD-MicroStrain/microstrain_inertial/files/12484014/new_firmware.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Architecture: x86_64
 - ROS Version: noetic

 - Firmware Version: 1.0.10
 - Sensor(s): 3DM-GQ7

**Modifications**
No

**Launch Parameters**
Attached

**Additional context**

**Comment by robbiefish** [comment]
Hi @ayoubasritii,

I apologize for not getting back to you sooner. The reason you would not have seen a difference after configuring the reference lever arm with SensorConnect is because the ROS driver will override that setting when we configure the device.

If you set [this line](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/3d3d678c0e2562151464d741094c75fd37705bf0/config/params.yml#L290) in your `microstrain.yaml` to your desired lever arm offset, that should give you the results you expect

**Comment by ayoubasritii** [comment]
Hello Rob,

Thanks for your answer, I will test it and let you know.
Do you think setting the reference to the rear axle is enough to tell the INS that is where the lateral velocity is null or I need to mention it by another mean?

Sincerely,
Ayoub.
________________________________
