### ISSUE TITLE
3DMGV7-AHRS is compatible??

### ISSUE THREAD

**Issue by eeoon** [LORD-MicroStrain/ROS-MSCL#281]
### **# ros2 launch microstrain_inertial_driver microstrain_launch.py** 

[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [microstrain_inertial_driver_node-1]: process started with pid [344]
[microstrain_inertial_driver_node-1] [INFO] [1698839403.829084098] [microstrain_inertial_driver]: Running microstrain_inertial_driver version: ros2-3.1.0
[microstrain_inertial_driver_node-1] [INFO] [1698839403.829231019] [microstrain_inertial_driver]: Using MIP SDK version: v1.0.0-42-gc332b1a
[microstrain_inertial_driver_node-1] [INFO] [1698839403.829282059] [microstrain_inertial_driver]: Attempting to open serial port </dev/ttyACM0> at <115200>
[microstrain_inertial_driver_node-1] [INFO] [1698839403.829825153] [microstrain_inertial_driver]: Setting device to idle in order to configure
[microstrain_inertial_driver_node-1] [INFO] [1698839403.832000938] [microstrain_inertial_driver]: Main Connection Info:
[microstrain_inertial_driver_node-1]     #######################
[microstrain_inertial_driver_node-1]     Model Name:       3DMGV7-AHRS
[microstrain_inertial_driver_node-1]     Serial Number:    6288.168747
[microstrain_inertial_driver_node-1]     Firmware Version: 1.1.00
[microstrain_inertial_driver_node-1]     #######################
[microstrain_inertial_driver_node-1] [INFO] [1698839403.832020370] [microstrain_inertial_driver]: Note: Not opening aux port because RTK dongle enable was not set to true.
[microstrain_inertial_driver_node-1] [INFO] [1698839403.832983218] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/aiding_status
[microstrain_inertial_driver_node-1] [INFO] [1698839403.832998398] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/antenna_offset_correction
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833003754] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/fix
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833010932] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/fix_info
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833015465] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/odom
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833019159] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/rf_error_detection
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833022801] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/sbas_info
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833026737] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss1/time_ref
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833030975] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/aiding_status
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833035180] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/antenna_offset_correction
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833039410] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/fix
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833042993] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/fix_info
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833046731] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/odom
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833051490] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/rf_error_detection
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833055101] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/sbas_info
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833058437] [microstrain_inertial_driver]: Note: The device does not support publishing the topic gnss2/time_ref
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833075525] [microstrain_inertial_driver]: Note: The device does not support publishing the topic nav/aiding_summary
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833080767] [microstrain_inertial_driver]: Note: The device does not support publishing the topic nav/dual_antenna_status
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833092612] [microstrain_inertial_driver]: Note: The device does not support publishing the topic nav/fix
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833099640] [microstrain_inertial_driver]: Note: The device does not support publishing the topic nav/heading_state
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833120100] [microstrain_inertial_driver]: Note: The device does not support publishing the topic rtk/status
[microstrain_inertial_driver_node-1] [INFO] [1698839403.833125814] [microstrain_inertial_driver]: Note: The device does not support publishing the topic rtk/status_v1
[microstrain_inertial_driver_node-1] [INFO] [1698839403.836076818] [microstrain_inertial_driver]: Note: Not configuring GPIO
### Why did this problem occur?

**Comment by robbiefish** [comment]
This appears to be the same issue as #273, specifically see [this comment](https://github.com/LORD-MicroStrain/microstrain_inertial/issues/273#issuecomment-1697980522) for a suggested fix
