### ISSUE TITLE
Ability to publish ECEF TF from earth

### ISSUE THREAD

**Issue by Aposhian** [LORD-MicroStrain/ROS-MSCL#284]
**Is your feature request related to a problem? Please describe.**
Currently, in order to use the ROS driver with TF, you have to use a relative position reference, but this shouldn't be a requirement.

**Describe the solution you'd like**
The current driver allows for publishing a TF from the relative position reference to the sensor. It would be great if you could also do this to publish a TF from the earth frame (ECEF origin) to the coordinates in ECEF.

**Describe alternatives you've considered**
Doing this in an extra component outside the driver that subscribes to the driver output and publishes TF.

**Additional context**
N/A

**Comment by robbiefish** [comment]
This was added in `4.0.0` please see the [Transforms](https://wiki.ros.org/microstrain_inertial_driver/transforms) page of our ROS wiki
