### ISSUE TITLE
DeclinationSource and TRANSITION_CONFIGURE failed with latest ros2 driver install.

### ISSUE THREAD

**Issue by PraanavFuturisticBots** [LORD-MicroStrain/ROS-MSCL#291]
I installed the latest ros2 microstrain inertial driver. I ran the following commands:
sudo apt-get update && sudo apt-get install ros-galactic-microstrain-inertial-driver  and
sudo apt-get update && sudo apt-get install ros-galactic-microstrain-inertial-rqt 

After that I am running the following command to publish the IMU data:
ros2 launch microstrain_inertial_driver microstrain_launch.py configure:=true activate:=true imu_frame_id:=imu_link use_enu_frame:=true

This command was working fine previously for publishing the data. But I am getting the following error:

[microstrain_inertial_driver_node-1] [INFO] [1705725402.176365177] [microstrain_inertial_driver]: Using MSCL Version: 64.2.2
[microstrain_inertial_driver_node-1] [INFO] [1705725402.177251450] [microstrain_inertial_driver]: Attempting to open serial port </dev/ttyACM0> at <115200>
[microstrain_inertial_driver_node-1] [INFO] [1705725402.182227990] [microstrain_inertial_driver]: Setting to Idle: Stopping data streams and/or waking from sleep
[microstrain_inertial_driver_node-1] [INFO] [1705725402.185933944] [microstrain_inertial_driver]: 
[microstrain_inertial_driver_node-1]       #######################
[microstrain_inertial_driver_node-1]       Model Name:    3DMCV7-AHRS
[microstrain_inertial_driver_node-1]       Serial Number: 6286.167849
[microstrain_inertial_driver_node-1]       #######################
[microstrain_inertial_driver_node-1]     
[microstrain_inertial_driver_node-1] [INFO] [1705725402.196987580] [microstrain_inertial_driver]: Setting Declination Source
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/microstrain_inertial_driver'
[microstrain_inertial_driver_node-1] [ERROR] [1705725402.198343434] [microstrain_inertial_driver]: Error: The DeclinationSource command has failed. (Error Code: 3)
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_ACTIVATE' for LifecycleNode '/microstrain_inertial_driver'
[microstrain_inertial_driver_node-1] [WARN] [1705725402.199967242] [rcl_lifecycle]: No transition matching 3 found for current state unconfigured 

After this, I tried to built the ros2 microstrain package from source. But got the same error
Please someone look into this issue.
Any help would be worthfull

**Comment by robbiefish** [comment]
Please see #168. Specifically [this](https://github.com/LORD-MicroStrain/microstrain_inertial/issues/168#issuecomment-1192737248) comment
