### ISSUE TITLE
Failed to configuere PPS source

### ISSUE THREAD

**Issue by gendebeat** [LORD-MicroStrain/ROS-MSCL#296]
I have some problem to conect with ROS. 
I install ros package with apt-install and configure parameters to /dev/microstrain_main because is not on default device.
I think is conected  because the node read model and serial number, but ros node exits. 
![image002](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/6656620/59ff35dc-19e5-4552-a3c0-8842257e3d1e)

**Comment by gendebeat** [comment]
ok, i put device_setup=false in param config file. It work for me because i use the current settings

**Comment by robbiefish** [comment]
See #273
