### ISSUE TITLE
3DM-GQ7 not subscribing to external velocity aiding

### ISSUE THREAD

**Issue by alexlin2** [LORD-MicroStrain/ROS-MSCL#298]
Hi, I have a question regarding fusing external body frame velocity with the INS unit 3DM-GQ7, in the ROS Wiki for microstain_inertial_driver 4.0.0, there is a subscription topic called /ext/velocity_body, which is described as "Will be enabled if subscribe_ext_vel_body is true and the device supports the body velocity aiding command. Will subscribe to external body velocity and send it to the device." I set the flag to be true, but the driver was not listening or subscribing to that topic. My understanding is that the GQ7 does support fusing external velocities, is that a bug or am I missing something?

**Environment:**
 - OS: Ubuntu 20.04
 - Architecture: x86_64
 - ROS Version: noetic
 - Version: 4.0.0
 - Sensor(s): 3DM-GQ7

**Comment by nathanmillermicrostrain** [comment]
Hi Alex,

The GQ7 does not support external body velocity measurements, unfortunately.  It supports external GNSS measurements, with position in the LLH frame and velocity in the NED frame.  It also supports an external speed measurement, but not a vector velocity measurement.  More can be found here: https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Commands/0x0d/0x0d_links.htm

Hope that helps,

Nathan
