### ISSUE TITLE
Config filename typo: `gx5_25.yml` vs `gx5_15.yml`

### ISSUE THREAD

**Issue by GreatAlexander** [LORD-MicroStrain/ROS-MSCL#320]
**Describe the bug**
Minor filename typo.
Config file should be `gx5_15.yml` not `gx5_25.yml` in the gx5_15 folder (ros2 branch).
https://github.com/LORD-MicroStrain/microstrain_inertial/blob/ros2/microstrain_inertial_examples/config/gx5_15/gx5_25.yml

**To Reproduce**
Launch the gx5_15 example launch file which points to a non-existent file.

**Expected behavior**
Example launch file works correctly

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: Docker [ros:humble-ros-base-jammy]
 - ROS Version: Humble
 - Version: Latest `ros2` branch [source]
 - Sensor(s): 3DM-GX5-15

**Additional context**
While setting up our [own launch repo](https://github.com/ipab-rad/imu/tree/init_config) based on the examples, we noticed this naming inconsistency. Apologies if this is not the right process / we've missed something.

**Comment by robbiefish** [comment]
Thanks for pointing that out and making the PR. Just merged
