### ISSUE TITLE
Launching error

### ISSUE THREAD

**Issue by ujasindro** [LORD-MicroStrain/ROS-MSCL#326]
I have Microstrain HBK IMU. MF number: 3DM-CV7-AHRS.

I have followed all the given steps to get the IMU started but when I am doing the launch command it is throwing and error saying that the device is not support and not giving me any data. I have attached the picture of the error I am having. Any help to solve this would be really appriciated.
![Screenshot from 2024-05-14 17-51-21](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/109538925/ebb55d25-96b6-46b4-b2a1-996fc64e34c0)

**Comment by robbiefish** [comment]
See #273

Alternatively, there is now a CV7 specific example which should resolve the issue you mentioned and can be launched with
```bash
ros2 launch microstrain_inertial_examples cv7_launch.py
```
