### ISSUE TITLE
3DM-GQ7 RTCM / NMEA configuration for external data

### ISSUE THREAD

**Issue by mschratter** [LORD-MicroStrain/ROS-MSCL#334]
I want to use an external ntrip server for the rtcm data. Previously I used another GNSS receiver with your [ntrip_client](https://github.com/LORD-MicroStrain/ntrip_client) to get the rtcm_msgs via the nmea_msgs message. 
If I read the documentation correctly, one way to get the rtcm data to the 3DM-GQ7 is to use the aux port via a second cable. Is this correct? 

If so, how do I configure the 3DM-GQ7 in the yaml to receive the nema message via ROS and how do I configure the ntrip_client node to send the rtcm data to the 3DM-GQ7 via the aux port, or does the microstrain_inertial_driver send the rtcm data to the 3DM-GQ7?

**Expected behavior**
Getting rtcm data on the  3DM-GQ7

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Architecture: x86_64
 - ROS Version: humble
 - Version: 4.3.0
 - Sensor(s): 3DM-GQ7

**Comment by Aposhian** [comment]
If you set the ROS param `ntrip_interface_enable: True` then it will subscribe to RTCM messages that the ntrip_client publishes, and write them to the aux port, as well as read NMEA sentences from the aux port and publish them for the ntrip_client.

https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/80378f949792743bdc15de1c549e7ff28d00004e/config/params.yml#L165-L168

**Comment by robbiefish** [comment]
Thanks for answering this @Aposhian. I am closing this issue.

Additionally, for a simple example of using `microstrain_inertial_driver` with the `ntrip_client`, check out [`microstrain_inertial_localization`](https://github.com/microstrain-robotics/microstrain_inertial_localization) and it's [wiki](https://wiki.ros.org/microstrain_inertial_localization) page, specifically the [NTRIP Settings](https://wiki.ros.org/microstrain_inertial_localization/gq7_odom#NTRIP_Settings) section
