### ISSUE TITLE
How to get GPS heading ?

### ISSUE THREAD

**Issue by PierreInnodura** [LORD-MicroStrain/ROS-MSCL#340]
Hello,
I'm currently using 3DM-GQ7 with two antennas, I'm struggling to convert the /ekf/odometry_earth message in the ECEF frame into the ENU frame to get the heading to north. Could you provide me some support on this topic please ?

**Comment by robbiefish** [comment]
ENU orientation can be found in the `pose.pose.orientation` field of the `/ekf/dual_antenna_heading` topic.

This topic can be enabled by setting `filter_dual_antenna_heading_data_rate` to a non-zero value

**Comment by PierreInnodura** [comment]
Thank you for your response, heading is only published when the two antennas have clear view of the sky ?

**Comment by robbiefish** [comment]
In the dual antenna heading topic, you will need to make sure that you have good sky view on both antennas and that the antenna offsets are configured correctly. We have a guide for how to properly measure antenna offsets in our documentation [here](https://files.microstrain.com/GQ7+User+Manual/user_manual_content/installation/Antenna.htm)

**Comment by PierreInnodura** [comment]
Ok , thank you very much !

**Comment by PierreInnodura** [comment]
Hello, just another question, once the ekf is initialized with the heading of the two antennas, the topic will continue to publish heading information without clear sky view of the two antennas ?
