### ISSUE TITLE
Pure orientation on tf tree

### ISSUE THREAD

**Issue by ebnerluca** [LORD-MicroStrain/ROS-MSCL#341]
Hello, 

I would like to read the orientation of my 3DM-CV7-AHRS from a tf topic or a pose publisher.
I followed the wiki and tried the following config for my ros node:
```
tf_mode: 2

[...]

filter_relative_position_config : True
filter_relative_position_frame  : 2
filter_relative_position_source : 2
filter_relative_position_ref    : [0.0, 0.0, 0.01]
```

According to the wiki (https://wiki.ros.org/microstrain_inertial_driver/transforms, section 2.3), this should now publish a static tf from `earth_frame_id -> map_frame_id` (this is working), and a dynamic tf from `map_frame_id -> target_frame_id` (this is not working).
Am I missing something? Do i need to somehow fake odometry in order to have a 'valid' full pose for the tf tree? I do not care about the position, only the orientation.

Thanks in advance.

**Comment by robbiefish** [comment]
Hello @ebnerluca, The 3DM-CV7-AHRS, and 3DM-CV7-AR devices do not support publishing any position information as they do not have a source for global position.

If you want to output a global position solution from our driver, you would need a device which supports outputting global position such as the [3DM-GQ7](https://www.microstrain.com/inertial-sensors/3dm-gq7) or a [3DM-CV7-INS](https://www.microstrain.com/inertial-sensors/3DM-CV7-INS) with an external receiver connected to provide global position
