### ISSUE TITLE
Collect Binary on Service Call

### ISSUE THREAD

**Issue by vinnnyr** [LORD-MicroStrain/ROS-MSCL#342]
**Is your feature request related to a problem? Please describe.**
Sometimes I observe behavior that I would like to collect a binary for, but currently that requires changing a ros parameter and then restarting the node, which might be disruptive to our current operation (i.e. monitoring a machine that cannot tolerate a restart of the node without erroring for safety reasons).

**Describe the solution you'd like**
It would be very very useful to be able to trigger a binary recording on and off via a service call so that we do not have to restart the driver if something about our binary desire changes. 

**Describe alternatives you've considered**
Some users may be able to keep their binaries always recording, but that is not acceptable to us as we have bandwidth constraints on our connection to the GQ7. 

**Additional context**
N/A.

**Comment by robbiefish** [comment]
This was added in `4.5.0`, see the [services](https://wiki.ros.org/microstrain_inertial_driver#Services) section of the wiki for more information
