### ISSUE TITLE
Confusion regarding cellular RTK Module corrections using 3rd party NTRIP host in ROS1

### ISSUE THREAD

**Issue by donceykong** [LORD-MicroStrain/ROS-MSCL#344]
Hey, so I am in the process of setting up RTK using ROS1 and I am a bit stuck on where to proceed.

I have successfully connected the new RTK modem to SensorCloud on a BASIC account and I believe I am getting NTRIP corrections, as the position of my modem is being updated correctly in SensorCloud. However, SensorCloud portal shows 0.00K/25.00K transactions for my device and rtk SensorCloud shows current NTRIP usage as "0 Minutes." Billing history shows no transactions. 

In SensorConnect, I am able to get "Full Nav" once my GPS recievers start getting signal. RTK shows a green light and updates, though the towers do change frequently.

Also, after setting up a config file for using Microstrain Inertial in ROS, I see that the “/mip/gnss_corrections/rtk_corrections_status” topic does in fact publish. I also see a terminal output with "full nave enabled" and initial lat/long coordinate. 

The “/mip/gnss_corrections/rtk_corrections_status” topic does not show corrected gps data however. Attached is an output of that topic. **What topic am I supposed to use to get the corrected RTK data?**

![Screenshot from 2024-07-21 16-43-09](https://github.com/user-attachments/assets/fecf889a-ac00-497c-b1a1-87da1bd436d8)

Thank you!

**Comment by robbiefish** [comment]
Hi @donceykong, the `microstrain_inertial_driver` does not provide raw RTCM data from the RTK receiver.

If you are asking what topics will have been corrected using RTK corrections:
* `/gnss_1/llh_position` and `/gnss_2/llh_position` will contain the position information produced directly by the GNSS receivers after receiving RTK corrections
* For a more complete, and likely accurate solution, `/ekf/llh_position`, `/ekf/odometry_earth`, and `/ekf/odometry_map` will contain the solution from our tightly coupled filter which uses GNSS data, IMU data, RTK corrections, and other onboard sensors

Given the screenshot you provided, as well as your description of a "green light" on the modem, it would appear that you are not yet receiving the corrections though. When the modem is receiving corrections, it will flash blue.

Here is a quick checklist of things to check to make sure that you are able to get corrections:
1. Do you have `rtk_dongle_enable` set to true in the driver configuration
2. Is the modem connected to the aux port of the GQ7?
3. Do you have GNSS antenna 1 connected and are in an area with good skyview?

If you have checked that all of those things are true, but are still unable to receive corrections (blue LED), please open a ticket on our [support portal](https://sensor.support.microstrain.com/servicedesk/customer/portals)
