### ISSUE TITLE
Possible issue with Euler angle calculation (Yaw and roll).

### ISSUE THREAD

**Issue by mzhouURI** [LORD-MicroStrain/ROS-MSCL#345]
**Describe the bug**
When setting use_enu_frame to true, we discover the Yaw angle will decrease when placed sensor with z-axis pointing downward and rotate the sensor counter-clockwise.
I also found in this placement, the roll angle is reporting zero. but in ENU should it report 180 deg? Or if roll is reporting 0 deg the counter clockwise rotation should result in yaw angle increase. 

**To Reproduce**
1. Launch Node with command  ` roslaunch microstrain_inertial_driver microstrain.launch`

**Expected behavior**
- Visualize yaw angle using `plotjuggler`. 
- place sensor with z-axis pointing down and turn it counter clockwise, yaw angle will decrease, roll report 0 deg
- place sensor with z-axis pointing up and turn it counter clockwise, yaw angle will increase, roll report 180deg

**Environment (please complete the following information):**
 - OS: ubuntu20.04
 - Architecture: x86_64
 - ROS Version: noetic
 - Version:  installed using `sudo apt install ros-noetic-microstrain-inertial-drive`
 - Sensor(s): 3DM-GX5-25

**Modifications**
I believe is the Euler angle calculation may be wrong?

**Launch Parameters**
standard param used in the launch file.

**Additional context**

**Comment by robbiefish** [comment]
This was indeed a bug, and should be fixed as of `4.4.0`. Please reopen this issue if the latest version does not fix this
