### ISSUE TITLE
Filter LLH message always reports NO_FIX on CV7

### ISSUE THREAD

**Issue by william-swarmbotics** [LORD-MicroStrain/ROS-MSCL#346]
**Describe the bug**
We have observed that the filter LLH message always reports a status of -1, or `NO_FIX`, even when the filter has an accurate fix and reports a stable status in `/ekf/status`. This causes issues with a downstream component we are using that is looking for a valid NavSatFix message.

We are using the CV7 INS on ROS2 with a GPS connected directly to the device GPIO.

**To Reproduce**
1. Set up a GPS device to send NMEA messages to the CV7.
2. Launch the ROS2 node with the attached params.
3. Inspect the `status.status` field of the NavSatFix message on topic `/ekf/llh_position`.

**Expected behavior**
The status field should report 0 (`STATUS_FIX`) when the filter has a valid fix.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: arm64
 - ROS Version: Humble
 - Version: 4.3.0
 - Sensor(s): 3DM-CV7

**Modifications**
None.

**Launch Parameters**
[microstrain_params.txt](https://github.com/user-attachments/files/16513983/microstrain_params.txt)

**Comment by robbiefish** [comment]
This should be fixed as of `4.4.0`, please reopen this issue if this is still an issue on the latest version
