### ISSUE TITLE
CV7 - ekf linear acceleration remains zero

### ISSUE THREAD

**Issue by skyrobos** [LORD-MicroStrain/ROS-MSCL#353]
**Describe the bug**
ekf/imu/data/linear_acceleration xyz values are always zero when `
filter_use_compensated_accel : false`
I moved the sensor and didn't see any change.
The non-filtered values change according to the movement

**To Reproduce**
1. Launch Node with command `roslaunch microstrain_inertial_driver microstrain.launch `
2. Move The IMU
3. The ekf linear acceleration remains zero

**Expected behavior**
see filtered values without gravity factor

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: arm64
 - ROS Version: noetic
 - Version: ros-4.3.0
 - Sensor(s): 3DM-CV7-AHRS

params file:
[params.txt](https://github.com/user-attachments/files/17059743/params.txt)

![ekf](https://github.com/user-attachments/assets/c6f6493a-e9ae-4662-88e9-8341fde02008)

**Comment by robbiefish** [comment]
This should be fixed as of `4.4.0`
