### ISSUE TITLE
GPIO Pin Functionality

### ISSUE THREAD

**Issue by smash0190** [LORD-MicroStrain/ROS-MSCL#358]
**Is your feature request related to a problem? Please describe.**
The GQ7 supports 4 GPIO pins (pps + regular GPIO pin usage) however currently they are not exposed in the ROS2 driver. They can only be configured during launch but then not changed anymor (as far as I could find).

**Describe the solution you'd like**
It would be awesome if there was either a message or service call that would expose both inputs and outputs for the pins set as GPIO input or output pins. This would simplify some use cases where having GPIO pins would require extra hardware or complex driver setup.

**Describe alternatives you've considered**
GPIO pin reading and setting could either be exposed as a message or service call that gets polled. Either approach is fine but there would probably be a slight preference towards messages.

This is related to this MIP command:
https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Commands/0x0c/data/0x42.htm?Highlight=gpio

**Comment by robbiefish** [comment]
Hi @smash0190, the GPIO state command has been added in `4.5.0`, see the [services](https://wiki.ros.org/microstrain_inertial_driver#Services) section of the wiki for more information
