### ISSUE TITLE
Dual Antenna Heading, EKF fusion

### ISSUE THREAD

**Issue by sif95** [LORD-MicroStrain/ROS-MSCL#359]
Hi, I would like to check does the ekf/imu/data orientation data fuses the gnss dual antenna heading info? or it is just using its magnometer? I am getting the dual antenna heading on the ekf/dual_antenna_heading topic. 
Thank you.

**Comment by robbiefish** [comment]
Hi @sif95, If [filter_enable_gnss_heading](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/951ab22d9a4ec4a4bb927d18ea39b25147908508/config/params.yml#L176) is set to true, then `/ekf/imu/data/orientation` will incorporate the measurements from the dual antenna heading system
