### ISSUE TITLE
No topic for '/imu/mag' and '/imu/pressure' for 3DM-CV7-AHRS using ROS2 Jazzy

### ISSUE THREAD

**Issue by Rhyssmcm** [LORD-MicroStrain/ROS-MSCL#366]
**Describe the bug**
Able to get topic list of "/ekf/status
                                     /imu/data
                                     /imu/data_raw
                                     /parameter_events
                                     /rosout
                                     /tf
                                     /tf_static"
However I want full access to all the topics available on my device, 3DM-CV7-AHRS, which has mag and pressure sensor. I would like information on how the .yml file can be changed to allow these topics to be published. I am reluctant to change my ROS2 version as Jazzy will be what I will be using over next 3 years, just unsure how the other topics can be grabbed and not the rest.

**To Reproduce**
1. Launch Node with command `cd your_workspace/
2. source install/setup.bash
3. ros2 launch microstrain_inertial_driver microstrain_launch.py params_file:="/home/rmcm/sensor_3dm_params.yml"`
4. using "ros2 topic list -t" I can see the topic list of some topics but not all. 
5. See Error

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04 using WSL2
 - ROS Version: Jazzy
 - Version: [e.g. 2.0.0]
 - Sensor(s): 3DM-CV7-AHRS

**Modifications**
Used custom .yml file in order to get it to work

**Launch Parameters**
If you have an updated `params.yml` file, please attach it to this issue.

**Additional context**
The .txt file is the .yml file but I could not attach the .yml file.
[sensor_3dm_params.txt](https://github.com/user-attachments/files/17834500/sensor_3dm_params.txt)

**Comment by robbiefish** [comment]
Hi @Rhyssmcm,

You can change the publisher data rates by changing any of the parameters in [this section](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/main/config/params.yml#L448-L518).

For the mag and pressure topics specifically, you can enable them by setting `imu_mag_data_rate`, and `imu_pressure_data_rate` to non-zero values
