### ISSUE TITLE
Drivers not compiling with the recent release of MSCL v61.1.6 

### ISSUE THREAD

**Issue by milievski** [LORD-MicroStrain/ROS-MSCL#39]
Using the most recent release of MSCL v61.1.6 causes the following errors:
```
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘state’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘statusCode’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘correctionsTimedOut’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘serviceUnavailable’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘modemPowered’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘cellConnected’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘serverConnected’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘dataEnabled’
error: ‘class mscl::RTKDeviceStatusFlags’ has no member named ‘rssi’
```

This is as a result of an API change of the RTKDeviceStatusFlags class in the most recent release found [here](https://github.com/LORD-MicroStrain/MSCL/blob/d56ab4ee9be89f3c09a0b6fdf0abc1763a56b843/MSCL/source/mscl/MicroStrain/Inertial/ExposedInertialTypes.h#L2340).

Would it be possible to get an update of the RTKDeviceStatusFlag interface to reflect the API changes?

**Comment by nathanmillerparker** [comment]
Hey Milievski,

This should be fixed in the latest commit.  Let me know if you have any issues.
