### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by RBarron01** [LORD-MicroStrain/ROS-MSCL#42]
Issue: When pulling ROS-MSCL, it no longer works to move ros_mscl to the workspace/src folder. This is in step 2 of "Building from Source."
Doing this results in error: 

`-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find mscl_msgs (missing: mscl_msgs_DIR)
-- Could not find the required component 'mscl_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
-- Configuring incomplete, errors occurred!`

Solution: move ROS-MSCL into the workspace/src file without removing anything from the folder.

**Comment by mglord** [comment]
Good catch - I'll confirm and update shortly! Thanks!
