### ISSUE TITLE
Symlinks to Serial Ports

### ISSUE THREAD

**Issue by Sanderi44** [LORD-MicroStrain/ROS-MSCL#5]
Thanks for the quick update on my previous issue! Here is another! In our system, it would be immensely useful to auto-detect the IMU connection and set it up on a named serial port like `/dev/imu` instead of `/dev/ttyUSB0` (which can vary). As per this [issue](https://github.com/LORD-MicroStrain/MSCL/issues/99) on the main MSCL repo, symlinks to serial ports do not work. As they mention in the issue, a simple workaround is to use the `realpath()` function from `stdlib.h`. 

Here is an example of how that might look [here](https://github.com/LORD-MicroStrain/ROS-MSCL/blob/de341443befa7ee6a041211dd6d6256123cc5149/ros_mscl/src/microstrain_3dm.cpp#L128):
```c++
#include <stdlib.h>
...
...
...
mscl::Connection connection = mscl::Connection::Serial(realpath(port.c_str()), baudrate);
```

**Comment by rdslord** [comment]
Thanks for letting us know! This should be working now.
