### ISSUE TITLE
Compilation problems caused by the latest version of the driver requires C++17

### ISSUE THREAD

**Issue by isValid** [LORD-MicroStrain/ROS-MSCL#6]
Hi,
Regarding the problem of driver compilation, I learned that c++ 17 is needed.
But our development environment is solidified to GCC5, c++17 cannot be supported.
I believe most users do not have such a high-level development environment.
So can you help solve this problem.
Thank you.

**Comment by rdslord** [comment]
The latest version should be compatible with GCC5.
