### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by edwardribbit** [LORD-MicroStrain/ROS-MSCL#60]
Hi, is there a simple way of suppressing the build warnings from catkin build?
![image](https://user-images.githubusercontent.com/80285574/119184750-c83dca80-ba43-11eb-9120-9740ea4b573f.png)

I tried adding the SYSTEM flag in cmakelists

include_directories(SYSTEM ... ) but that didn't work.

**Comment by nathanmillerparker** [comment]
We haven't looked at what it would take to do this.

**Comment by edwardribbit** [comment]
It's definitely not top priority, but one could go through the process of casting types to the expected type

**Comment by nathanmillerparker** [comment]
I'll take a look at getting these cleaned up

**Comment by nathanmillerparker** [comment]
Ok... pushed a new version... let me know if you have any further issues
