### ISSUE TITLE
calibration of intrinsic parameters

### ISSUE THREAD

**Issue by linzha0** [LORD-MicroStrain/ROS-MSCL#61]
Hi, I am trying use gx5-25 for camera-imu extrinsic calibration using [kalibr](https://github.com/ethz-asl/kalibr/wiki/camera-imu-calibration). Before feed the data into kalibr, I need make sure all intrinsic parameters are calibrated. 

I found in #52 , it helped but I still have some questions, hope you can help me:

- you said scale-factor is applied in EKF. How about others, like axis misalignment, nonlinearities? 
- you also mentioned scale-factor only works when state is enabled. How can I enable it?

Thanks.

**Comment by nathanmillerparker** [comment]
The GX5-25 does not have scale-factor states that can be enabled.  The other parameters have been calibrated in the factory and assuming that the device has been handled correctly, will be still be valid.

Hope that helps,

Nathan
