### ISSUE TITLE
Different orientation values for raw imu compared with the filtered imu data

### ISSUE THREAD

**Issue by Aussie25** [LORD-MicroStrain/ROS-MSCL#74]
Hi, 
I was comparing the orientation values from the raw imu data as well as filtered imu data. The orientation values are totally different but the linear acceleration and angular velocity are identical. 

Orientation
![image](https://user-images.githubusercontent.com/91187845/138061550-d4c00938-c2ca-4295-992b-0517070fb4aa.png)

Angular velocity 
![image](https://user-images.githubusercontent.com/91187845/138061685-5acb2bc2-fb07-4323-a176-5cca09104e05.png)

Linear acceleration
![image](https://user-images.githubusercontent.com/91187845/138061784-5d638d4d-5ed6-4a1a-8f01-9fc2f5e1cc4c.png)

**Comment by JiulongGao** [comment]
Hello, I have the same problem. How can I get an accurate filtered IMU！
