### ISSUE TITLE
On the issue frequency of filtered data

### ISSUE THREAD

**Issue by isValid** [LORD-MicroStrain/ROS-MSCL#8]
Hi,I found a new problem in the test. The data before filtering (/imu/data) takes a few seconds to stabilize after the IMU rotates, so I chose the data after filtering (/filtered/imu/data), However, the data release frequency after filtering is only 10 Hz, and it seems that the release frequency cannot be modified. Can you increase the data release frequency after filtering?

**Comment by rdslord** [comment]
There is a parameter in the launch file called nav_rate. To change the rate of the filtered data, change that value in the launch file.

**Comment by isValid** [comment]
it's ok, thank you!
