### ISSUE TITLE
gravity measurement confusion 

### ISSUE THREAD

**Issue by linzha0** [LORD-MicroStrain/ROS-MSCL#97]
Hi, the driver version I am using is 1.1.3 with native frame which is NED. When the AHRS is not moving and stand on the desktop. The z-axis measurement is around -9.81. I am just wondering this is correct. In my conscious, the Z-axis is pointing down and the gravity is pointing down, is that should be 9.81? Or the IMU is just measure the oppose force of gravity, that's make the measurement negative. 

Thanks for the help.

**Comment by nathanmillermicrostrain** [comment]
Accelerometers measure the normal force with respect to gravity.... so -9.81 does make sense.  If the device is not moving and you do a vector addition with the gravity vector, you will get approximately 0 acceleration... which is the correct value.
